### ISSUE TITLE
Acrylic DNS Prevents WSL Bash from Starting

### ISSUE THREAD

**Issue by darrylmorley** [valeryan/valet-wsl#3] opened 2019-06-23 18:18 UTC
When restarting my pc I am unable to run wsl or open my Hyper terminal. The Acrylic DNS service prevents the loading of Bash.

**Comment by valeryan** [comment] 2019-06-23 18:31
I would guess you have a problem with your DNS configuration. I would just use the windows hosts file in your case. Maybe contact the developer of Acrylic DNS.

**Comment by darrylmorley** [comment] 2019-06-23 22:15
I think possibly an issue with WSL2...

I have reverted to WSL1 and followed the install steps, valet will not start, valet status constantly indicates nginx and fpm have stopped. However the service for nginx is definitely running.

**Comment by valeryan** [comment] 2019-06-24 04:27
Not sure what you are experiencing. I just went through the setup process on a fresh wsl install and everything started up fine and the laravel site was served. I did have to make a few adjustments to the setup process and add `fastcgi_buffering off;` all my Nginx configs. I will make a patch to add that tomorrow sometime. If I was to guess it sounds like you might have some port blocking. When I have issues with the services it is usually something to do with windows and linux fighting over a port.

**Comment by darrylmorley** [comment] 2019-06-24 08:39
Hi,

My apologies for wasting your time, I now have everything running as it should. 

I believe that my issue was related to using WSL2. I have reverted to WSL1 and everything set up just fine.

I was also expecting 'valet status' to return a positive result when everything was running as it should, seems it doesn't matter as it still returns that nginx and php-fpm are stopped, but eveything is working.

Thanks for the quick responses!

**Comment by valeryan** [comment] 2019-06-24 11:54
I am running the current windows release. I haven't looked into wsl 2. I assume that is the version with a full Linux kernel. I will have to do testing. I will look at valet status and see if it's broken.

**Comment by valeryan** [comment] 2019-06-24 13:20
I see why that status check fails. I have a few things to test but I will get it fixed.

**Comment by nvahalik** [comment] 2019-06-26 02:16
Confirmed that Acrylic causes issues with WSL 2.0: https://github.com/microsoft/WSL/issues/4112

**Comment by valeryan** [comment] 2019-07-02 13:40
I am going to close this because the original issues is a WSL 2 issue and I have a fix for the status issue in the works. Thanks.

**Closed as completed by valeryan** 2019-07-02 13:40 UTC
